export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const LOADING_PRODUCTS_SUCCESS = 'LOADING_PRODUCTS_SUCCESS';
export const LOADING_PRODUCTS_ERROR = 'LOADING_PRODUCTS_ERROR';

export const GET_DELETE_PROYECT = 'GET_DELETE_PROYECT';
export const DELETE_PROYECT_SUCCESS = 'DELETE_PROYECT_SUCCESS';
export const DELETE_PROYECT_ERROR = 'DELETE_PROYECT_ERROR';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';